export type PointOfInterest = {
  name: string;
  type: "transit" | "school" | "park" | "shopping" | "landmark" | "restaurant";
  lat: number;
  lng: number;
  description?: string;
};

export type NeighbourhoodData = {
  name: string;
  slug: string;
  center: { lat: number; lng: number };
  zoom: number;
  tagline: string;
  avgPrice: string;
  priceChange: string;
  walkScore: number;
  transitScore: number;
  highlights: string[];
  /** Minimal fallback POIs for chat map cards (full POIs fetched via Places API) */
  fallbackPOIs: PointOfInterest[];
  bounds?: {
    north: number;
    south: number;
    east: number;
    west: number;
  };
};

export const NEIGHBOURHOODS: Record<string, NeighbourhoodData> = {
  oakridge: {
    name: "Oakridge",
    slug: "oakridge",
    center: { lat: 49.2220, lng: -123.1167 },
    zoom: 14,
    tagline: "Vancouver's Most Exciting Transformation",
    avgPrice: "$1.49M",
    priceChange: "-11.1% YoY",
    walkScore: 78,
    transitScore: 85,
    highlights: [
      "Oakridge Park redevelopment (3,300+ homes)",
      "Canada Line SkyTrain access",
      "Queen Elizabeth Park",
      "Top-rated schools (Churchill Secondary)",
    ],
    bounds: { north: 49.2375, south: 49.2175, east: -123.1000, west: -123.1350 },
    fallbackPOIs: [
      { name: "Oakridge-41st Avenue Station", type: "transit", lat: 49.2293, lng: -123.1167, description: "Canada Line SkyTrain, 15 min to Downtown" },
      { name: "Langara-49th Avenue Station", type: "transit", lat: 49.2262, lng: -123.1108, description: "Canada Line SkyTrain" },
      { name: "Oakridge Park Redevelopment", type: "landmark", lat: 49.2275, lng: -123.1167, description: "$6B mixed-use development with 3,300+ new homes and a 9-acre park" },
    ],
  },
  marpole: {
    name: "Marpole",
    slug: "marpole",
    center: { lat: 49.2100, lng: -123.1300 },
    zoom: 14,
    tagline: "Historic Charm Meets Modern Living",
    avgPrice: "$1.14M",
    priceChange: "-18.4% YoY",
    walkScore: 72,
    transitScore: 78,
    highlights: [
      "Most affordable westside neighbourhood",
      "Fraser River waterfront",
      "Growing dining scene on Granville",
      "Direct YVR access via Canada Line",
    ],
    bounds: { north: 49.2200, south: 49.2000, east: -123.1100, west: -123.1500 },
    fallbackPOIs: [
      { name: "Marine Drive Station", type: "transit", lat: 49.2098, lng: -123.1200, description: "Canada Line SkyTrain, connects to YVR & Downtown" },
      { name: "Fraser River Park", type: "park", lat: 49.2020, lng: -123.1270, description: "Waterfront trails with river views" },
      { name: "Marpole Community Centre", type: "landmark", lat: 49.2098, lng: -123.1316, description: "Community programs, fitness, and events" },
    ],
  },
  "south-cambie": {
    name: "South Cambie",
    slug: "south-cambie",
    center: { lat: 49.2480, lng: -123.1150 },
    zoom: 14,
    tagline: "Where Families Put Down Roots",
    avgPrice: "$1.44M",
    priceChange: "-15.5% YoY",
    walkScore: 80,
    transitScore: 82,
    highlights: [
      "Cambie Village shopping district",
      "Canada Line stations",
      "Douglas Park community centre",
      "Heritage home character",
    ],
    bounds: { north: 49.2550, south: 49.2350, east: -123.1000, west: -123.1300 },
    fallbackPOIs: [
      { name: "King Edward Station", type: "transit", lat: 49.2490, lng: -123.1158, description: "Canada Line SkyTrain" },
      { name: "Douglas Park", type: "park", lat: 49.2476, lng: -123.1085, description: "Community park with playground, pool, and sports fields" },
      { name: "Cambie Village", type: "shopping", lat: 49.2510, lng: -123.1150, description: "Vibrant local shopping and dining district" },
    ],
  },
  "riley-park": {
    name: "Riley Park",
    slug: "riley-park",
    center: { lat: 49.2420, lng: -123.1000 },
    zoom: 14,
    tagline: "Creative Energy & Community Spirit",
    avgPrice: "$1.70M",
    priceChange: "-9.4% YoY",
    walkScore: 82,
    transitScore: 75,
    highlights: [
      "Nat Bailey Stadium neighbourhood",
      "Hillcrest Community Centre & pool",
      "Main Street proximity",
      "Strong community feel",
    ],
    bounds: { north: 49.2520, south: 49.2320, east: -123.0850, west: -123.1150 },
    fallbackPOIs: [
      { name: "Nat Bailey Stadium", type: "landmark", lat: 49.2425, lng: -123.1015, description: "Historic baseball stadium, home of the Vancouver Canadians" },
      { name: "Hillcrest Community Centre", type: "landmark", lat: 49.2435, lng: -123.1050, description: "Aquatic centre, ice rink, and fitness facilities" },
      { name: "Riley Park", type: "park", lat: 49.2440, lng: -123.0960, description: "The neighbourhood's namesake park with sports fields" },
    ],
  },
  kerrisdale: {
    name: "Kerrisdale",
    slug: "kerrisdale",
    center: { lat: 49.2330, lng: -123.1570 },
    zoom: 14,
    tagline: "Upscale Village Living",
    avgPrice: "$1.90M",
    priceChange: "-15.1% YoY",
    walkScore: 85,
    transitScore: 72,
    highlights: [
      "Village shopping on 41st Avenue",
      "Tree-lined streets",
      "Top school catchments",
      "Arbutus Greenway access",
    ],
    bounds: { north: 49.2430, south: 49.2230, east: -123.1420, west: -123.1720 },
    fallbackPOIs: [
      { name: "Kerrisdale Village", type: "shopping", lat: 49.2340, lng: -123.1560, description: "Boutique shopping and dining on 41st Avenue" },
      { name: "Kerrisdale Arena", type: "landmark", lat: 49.2330, lng: -123.1600, description: "Community ice rink and recreation" },
      { name: "Arbutus Greenway", type: "park", lat: 49.2340, lng: -123.1540, description: "Multi-use trail for walking and cycling" },
    ],
  },
  "cambie-corridor": {
    name: "Cambie Corridor",
    slug: "cambie-corridor",
    center: { lat: 49.2300, lng: -123.1150 },
    zoom: 13,
    tagline: "Transit-Oriented Growth",
    avgPrice: "$1.46M",
    priceChange: "-19.8% YoY",
    walkScore: 81,
    transitScore: 88,
    highlights: [
      "Highest transit connectivity",
      "Rapid development corridor",
      "Multiple Canada Line stations",
      "New condo and townhome supply",
    ],
    bounds: { north: 49.2600, south: 49.2100, east: -123.1050, west: -123.1250 },
    fallbackPOIs: [
      { name: "Oakridge-41st Avenue Station", type: "transit", lat: 49.2293, lng: -123.1167, description: "Canada Line SkyTrain" },
      { name: "King Edward Station", type: "transit", lat: 49.2490, lng: -123.1158, description: "Canada Line SkyTrain" },
      { name: "Cambie Heritage Boulevard", type: "landmark", lat: 49.2400, lng: -123.1150, description: "Tree-lined boulevard with heritage character" },
    ],
  },
  kitsilano: {
    name: "Kitsilano",
    slug: "kitsilano",
    center: { lat: 49.2680, lng: -123.1680 },
    zoom: 14,
    tagline: "Beach Living & Urban Energy",
    avgPrice: "$1.25M",
    priceChange: "-8.0% YoY",
    walkScore: 88,
    transitScore: 80,
    highlights: [
      "Kitsilano Beach & Jericho Beach",
      "West 4th Avenue shopping & dining",
      "Strong cycling & outdoor culture",
      "Close to UBC and downtown",
    ],
    bounds: { north: 49.2780, south: 49.2580, east: -123.1400, west: -123.1900 },
    fallbackPOIs: [
      { name: "Kitsilano Beach", type: "park", lat: 49.2734, lng: -123.1536, description: "Iconic beach with outdoor saltwater pool and volleyball courts" },
      { name: "West 4th Avenue", type: "shopping", lat: 49.2680, lng: -123.1600, description: "Popular shopping and dining strip" },
      { name: "Jericho Beach", type: "park", lat: 49.2726, lng: -123.1970, description: "Sandy beach with sailing centre and mountain views" },
    ],
  },
  ubc: {
    name: "UBC",
    slug: "ubc",
    center: { lat: 49.2606, lng: -123.2460 },
    zoom: 14,
    tagline: "World-Class Campus & Community",
    avgPrice: "$1.35M",
    priceChange: "-18.9% YoY",
    walkScore: 70,
    transitScore: 65,
    highlights: [
      "University of British Columbia campus",
      "Pacific Spirit Regional Park",
      "Museum of Anthropology",
      "Wreck Beach & Spanish Banks",
    ],
    bounds: { north: 49.2800, south: 49.2400, east: -123.2100, west: -123.2700 },
    fallbackPOIs: [
      { name: "UBC Bus Exchange", type: "transit", lat: 49.2685, lng: -123.2460, description: "Major transit hub connecting to downtown" },
      { name: "Pacific Spirit Regional Park", type: "park", lat: 49.2550, lng: -123.2280, description: "763-hectare forest park with 73km of trails" },
      { name: "Museum of Anthropology", type: "landmark", lat: 49.2697, lng: -123.2595, description: "World-renowned museum featuring Northwest Coast Indigenous art" },
    ],
  },
  "arbutus-ridge": {
    name: "Arbutus Ridge",
    slug: "arbutus-ridge",
    center: { lat: 49.2490, lng: -123.1560 },
    zoom: 14,
    tagline: "Upscale Living on the Greenway",
    avgPrice: "$2.20M",
    priceChange: "-7.9% YoY",
    walkScore: 93,
    transitScore: 70,
    highlights: [
      "Arbutus Greenway trail",
      "Arbutus Village shopping",
      "Heritage homes on large lots",
      "Between Kerrisdale & Shaughnessy",
    ],
    bounds: { north: 49.2590, south: 49.2390, east: -123.1410, west: -123.1710 },
    fallbackPOIs: [
      { name: "Arbutus Village", type: "shopping", lat: 49.2490, lng: -123.1535, description: "Local shopping centre with grocery and retail" },
      { name: "Arbutus Greenway", type: "park", lat: 49.2500, lng: -123.1540, description: "Multi-use trail for walking and cycling" },
      { name: "Quilchena Park", type: "park", lat: 49.2520, lng: -123.1570, description: "Expansive playing fields and community recreation" },
    ],
  },
  "dunbar-southlands": {
    name: "Dunbar-Southlands",
    slug: "dunbar-southlands",
    center: { lat: 49.2440, lng: -123.1870 },
    zoom: 14,
    tagline: "Family Living Near UBC & Pacific Spirit",
    avgPrice: "$2.50M",
    priceChange: "-17.4% YoY",
    walkScore: 72,
    transitScore: 60,
    highlights: [
      "Dunbar Village on Dunbar Street",
      "Adjacent to Pacific Spirit Park",
      "Minutes to UBC",
      "Spacious lots and family homes",
    ],
    bounds: { north: 49.2590, south: 49.2290, east: -123.1700, west: -123.2100 },
    fallbackPOIs: [
      { name: "Dunbar Village", type: "shopping", lat: 49.2490, lng: -123.1865, description: "Charming neighbourhood shopping on Dunbar Street" },
      { name: "Pacific Spirit Regional Park", type: "park", lat: 49.2550, lng: -123.2050, description: "763-hectare forest park with 73km of trails" },
      { name: "Musqueam Park", type: "park", lat: 49.2350, lng: -123.1960, description: "Green space along the Fraser River area" },
    ],
  },
  shaughnessy: {
    name: "Shaughnessy",
    slug: "shaughnessy",
    center: { lat: 49.2490, lng: -123.1370 },
    zoom: 14,
    tagline: "Vancouver's Most Prestigious Address",
    avgPrice: "$3.50M",
    priceChange: "-18.5% YoY",
    walkScore: 65,
    transitScore: 60,
    highlights: [
      "Heritage mansions & estates",
      "VanDusen Botanical Garden",
      "Tree-lined boulevards",
      "First & Second Shaughnessy districts",
    ],
    bounds: { north: 49.2590, south: 49.2390, east: -123.1220, west: -123.1520 },
    fallbackPOIs: [
      { name: "VanDusen Botanical Garden", type: "park", lat: 49.2388, lng: -123.1296, description: "22-hectare botanical garden with over 7,500 plant species" },
      { name: "Shaughnessy Park", type: "park", lat: 49.2480, lng: -123.1380, description: "Quiet neighbourhood park in the heart of Shaughnessy" },
      { name: "Crescent Park", type: "park", lat: 49.2510, lng: -123.1340, description: "Small heritage park along The Crescent" },
    ],
  },
  "west-point-grey": {
    name: "West Point Grey",
    slug: "west-point-grey",
    center: { lat: 49.2680, lng: -123.2030 },
    zoom: 14,
    tagline: "Beaches, Views & Campus Living",
    avgPrice: "$2.30M",
    priceChange: "-7.7% YoY",
    walkScore: 78,
    transitScore: 68,
    highlights: [
      "Spanish Banks & Jericho Beach",
      "Minutes to UBC",
      "Character homes with views",
      "10th Avenue shopping",
    ],
    bounds: { north: 49.2780, south: 49.2580, east: -123.1850, west: -123.2200 },
    fallbackPOIs: [
      { name: "Spanish Banks Beach", type: "park", lat: 49.2756, lng: -123.2180, description: "Expansive sandy beach with mountain and ocean views" },
      { name: "Jericho Beach", type: "park", lat: 49.2726, lng: -123.1970, description: "Popular beach with sailing centre" },
      { name: "Trimble Park", type: "park", lat: 49.2660, lng: -123.2030, description: "Neighbourhood park with playground and sports fields" },
    ],
  },
  "grandview-woodland": {
    name: "Grandview-Woodland",
    slug: "grandview-woodland",
    center: { lat: 49.2720, lng: -123.0700 },
    zoom: 14,
    tagline: "Eclectic Culture on The Drive",
    avgPrice: "$1.10M",
    priceChange: "-9.2% YoY",
    walkScore: 90,
    transitScore: 92,
    highlights: [
      "Commercial Drive multicultural dining & shops",
      "Commercial-Broadway SkyTrain hub",
      "Britannia Community Centre",
      "Vibrant arts and indie scene",
    ],
    bounds: { north: 49.2820, south: 49.2620, east: -123.0550, west: -123.0850 },
    fallbackPOIs: [
      { name: "Commercial-Broadway Station", type: "transit", lat: 49.2626, lng: -123.0694, description: "Busiest SkyTrain station - Expo & Millennium Lines" },
      { name: "Grandview Park", type: "park", lat: 49.2750, lng: -123.0700, description: "Community park with playground and sports courts" },
      { name: "Commercial Drive", type: "shopping", lat: 49.2720, lng: -123.0700, description: "Iconic multicultural shopping and dining strip" },
    ],
  },
  "hastings-sunrise": {
    name: "Hastings-Sunrise",
    slug: "hastings-sunrise",
    center: { lat: 49.2810, lng: -123.0440 },
    zoom: 14,
    tagline: "Diverse Community with Heritage Roots",
    avgPrice: "$1.20M",
    priceChange: "-6.9% YoY",
    walkScore: 85,
    transitScore: 78,
    highlights: [
      "PNE/Playland & Pacific Coliseum",
      "Hastings Street shopping",
      "Affordable east-side character homes",
      "New Brighton Park waterfront",
    ],
    bounds: { north: 49.2910, south: 49.2710, east: -123.0240, west: -123.0640 },
    fallbackPOIs: [
      { name: "Hastings Park / PNE", type: "landmark", lat: 49.2833, lng: -123.0383, description: "Home of the PNE fair, Playland, and Pacific Coliseum" },
      { name: "New Brighton Park", type: "park", lat: 49.2880, lng: -123.0310, description: "Waterfront park with pool and harbour views" },
      { name: "Renfrew Station", type: "transit", lat: 49.2590, lng: -123.0454, description: "Expo Line SkyTrain station" },
    ],
  },
  "kensington-cedar-cottage": {
    name: "Kensington-Cedar Cottage",
    slug: "kensington-cedar-cottage",
    center: { lat: 49.2480, lng: -123.0750 },
    zoom: 14,
    tagline: "Diverse Family Living at Trout Lake",
    avgPrice: "$1.15M",
    priceChange: "-6.8% YoY",
    walkScore: 80,
    transitScore: 75,
    highlights: [
      "Trout Lake / John Hendry Park",
      "Kingsway restaurant corridor",
      "One of Vancouver's largest neighbourhoods",
      "Strong multicultural community",
    ],
    bounds: { north: 49.2580, south: 49.2380, east: -123.0550, west: -123.0950 },
    fallbackPOIs: [
      { name: "Trout Lake / John Hendry Park", type: "park", lat: 49.2560, lng: -123.0655, description: "Popular lake with farmers market, beach, and community centre" },
      { name: "Kensington Park", type: "park", lat: 49.2480, lng: -123.0740, description: "Neighbourhood park with community centre and arena" },
      { name: "Joyce-Collingwood Station", type: "transit", lat: 49.2385, lng: -123.0318, description: "Expo Line SkyTrain station" },
    ],
  },
  downtown: {
    name: "Downtown",
    slug: "downtown",
    center: { lat: 49.2827, lng: -123.1207 },
    zoom: 14,
    tagline: "Vancouver's Urban Core",
    avgPrice: "$750K",
    priceChange: "-7.2% YoY",
    walkScore: 98,
    transitScore: 100,
    highlights: [
      "Robson Street shopping district",
      "Gastown & Vancouver Art Gallery",
      "BC Place & Rogers Arena",
      "Coal Harbour waterfront",
    ],
    bounds: { north: 49.2920, south: 49.2730, east: -123.0950, west: -123.1400 },
    fallbackPOIs: [
      { name: "Waterfront Station", type: "transit", lat: 49.2857, lng: -123.1116, description: "SkyTrain hub & SeaBus terminal" },
      { name: "Vancouver Art Gallery", type: "landmark", lat: 49.2830, lng: -123.1207, description: "Major public art museum in Robson Square" },
      { name: "Coal Harbour Seawall", type: "park", lat: 49.2900, lng: -123.1230, description: "Scenic waterfront walkway with mountain views" },
    ],
  },
  fairview: {
    name: "Fairview",
    slug: "fairview",
    center: { lat: 49.2640, lng: -123.1300 },
    zoom: 14,
    tagline: "Central Living on the Broadway Corridor",
    avgPrice: "$900K",
    priceChange: "+0.6% YoY",
    walkScore: 95,
    transitScore: 90,
    highlights: [
      "Broadway Plan development corridor",
      "South Granville shopping",
      "City Hall & Cambie Village",
      "Granville Island adjacent",
    ],
    bounds: { north: 49.2720, south: 49.2560, east: -123.1100, west: -123.1500 },
    fallbackPOIs: [
      { name: "Broadway-City Hall Station", type: "transit", lat: 49.2633, lng: -123.1148, description: "Canada Line & future Broadway Subway interchange" },
      { name: "Granville Island", type: "landmark", lat: 49.2712, lng: -123.1340, description: "Public market, artisan shops, and cultural hub" },
      { name: "Jonathan Rogers Park", type: "park", lat: 49.2630, lng: -123.1100, description: "Heritage neighbourhood park with playground and wading pool" },
    ],
  },
  "west-end": {
    name: "West End",
    slug: "west-end",
    center: { lat: 49.2870, lng: -123.1340 },
    zoom: 14,
    tagline: "Vibrant Urban Beach Living",
    avgPrice: "$680K",
    priceChange: "-9.1% YoY",
    walkScore: 97,
    transitScore: 88,
    highlights: [
      "English Bay & Sunset Beach",
      "Davie Village LGBTQ+ hub",
      "Steps from Stanley Park",
      "Denman Street dining",
    ],
    bounds: { north: 49.2950, south: 49.2790, east: -123.1200, west: -123.1500 },
    fallbackPOIs: [
      { name: "English Bay Beach", type: "park", lat: 49.2863, lng: -123.1433, description: "Iconic urban beach with stunning sunsets" },
      { name: "Burrard Station", type: "transit", lat: 49.2857, lng: -123.1207, description: "Expo Line SkyTrain station" },
      { name: "Davie Village", type: "shopping", lat: 49.2820, lng: -123.1310, description: "Vibrant LGBTQ+ neighbourhood with shops and restaurants" },
    ],
  },
  "mount-pleasant": {
    name: "Mount Pleasant",
    slug: "mount-pleasant",
    center: { lat: 49.2620, lng: -123.1000 },
    zoom: 14,
    tagline: "Creative Culture & Craft Breweries",
    avgPrice: "$850K",
    priceChange: "+1.3% YoY",
    walkScore: 92,
    transitScore: 82,
    highlights: [
      "Main Street shopping & dining",
      "Craft brewery district",
      "Public art & murals",
      "Growing tech hub",
    ],
    bounds: { north: 49.2700, south: 49.2530, east: -123.0850, west: -123.1150 },
    fallbackPOIs: [
      { name: "Main Street-Science World Station", type: "transit", lat: 49.2733, lng: -123.1006, description: "Expo Line SkyTrain station" },
      { name: "Guelph Park (Dude Chilling Park)", type: "park", lat: 49.2595, lng: -123.0940, description: "Popular neighbourhood park with public art" },
      { name: "Main Street", type: "shopping", lat: 49.2620, lng: -123.1010, description: "Eclectic shops, restaurants, and cafes" },
    ],
  },
  killarney: {
    name: "Killarney",
    slug: "killarney",
    center: { lat: 49.2230, lng: -123.0440 },
    zoom: 14,
    tagline: "Family-Friendly Southeast Vancouver",
    avgPrice: "$1.10M",
    priceChange: "-8.8% YoY",
    walkScore: 78,
    transitScore: 72,
    highlights: [
      "Killarney Community Centre (one of Vancouver's best)",
      "Diverse multicultural community",
      "Excellent value real estate",
      "Everett Crowley Park",
    ],
    bounds: { north: 49.2330, south: 49.2130, east: -123.0240, west: -123.0640 },
    fallbackPOIs: [
      { name: "Killarney Community Centre", type: "landmark", lat: 49.2230, lng: -123.0440, description: "Award-winning community centre with pool, rink, and fitness" },
      { name: "Killarney Park", type: "park", lat: 49.2235, lng: -123.0430, description: "Central neighbourhood park adjacent to the community centre" },
      { name: "Everett Crowley Park", type: "park", lat: 49.2150, lng: -123.0430, description: "Naturalized park with trails and city views" },
    ],
  },
  "renfrew-collingwood": {
    name: "Renfrew-Collingwood",
    slug: "renfrew-collingwood",
    center: { lat: 49.2450, lng: -123.0380 },
    zoom: 14,
    tagline: "Vancouver's Most Diverse Community",
    avgPrice: "$1.05M",
    priceChange: "-10.5% YoY",
    walkScore: 82,
    transitScore: 80,
    highlights: [
      "3 SkyTrain stations (Expo Line)",
      "Multicultural food scene on Kingsway",
      "Collingwood Village",
      "Renfrew Ravine Park",
    ],
    bounds: { north: 49.2550, south: 49.2350, east: -123.0180, west: -123.0580 },
    fallbackPOIs: [
      { name: "Renfrew Station", type: "transit", lat: 49.2589, lng: -123.0454, description: "Expo Line SkyTrain station" },
      { name: "Rupert Station", type: "transit", lat: 49.2610, lng: -123.0330, description: "Expo Line SkyTrain station" },
      { name: "Renfrew Ravine Park", type: "park", lat: 49.2470, lng: -123.0430, description: "Forested ravine with trails and Still Creek" },
    ],
  },
  sunset: {
    name: "Sunset",
    slug: "sunset",
    center: { lat: 49.2230, lng: -123.0940 },
    zoom: 14,
    tagline: "Multicultural Heart of South Vancouver",
    avgPrice: "$1.30M",
    priceChange: "-8.7% YoY",
    walkScore: 75,
    transitScore: 68,
    highlights: [
      "Punjabi Market on Main Street",
      "Diverse food scene",
      "Quiet residential streets",
      "Affordable detached homes",
    ],
    bounds: { north: 49.2330, south: 49.2130, east: -123.0740, west: -123.1140 },
    fallbackPOIs: [
      { name: "Punjabi Market", type: "shopping", lat: 49.2230, lng: -123.1010, description: "Historic South Asian shopping and dining district on Main Street" },
      { name: "Sunset Park", type: "park", lat: 49.2240, lng: -123.0910, description: "Neighbourhood park with playground and sports fields" },
      { name: "Moberly Park", type: "park", lat: 49.2200, lng: -123.0870, description: "Community park with arts centre" },
    ],
  },
  "victoria-fraserview": {
    name: "Victoria-Fraserview",
    slug: "victoria-fraserview",
    center: { lat: 49.2250, lng: -123.0650 },
    zoom: 14,
    tagline: "River Views & Established Living",
    avgPrice: "$1.20M",
    priceChange: "-6.5% YoY",
    walkScore: 72,
    transitScore: 65,
    highlights: [
      "Fraserview Golf Course",
      "Fraser River views",
      "Victoria Drive shopping",
      "Everett Crowley Park",
    ],
    bounds: { north: 49.2350, south: 49.2150, east: -123.0450, west: -123.0850 },
    fallbackPOIs: [
      { name: "Fraserview Golf Course", type: "park", lat: 49.2200, lng: -123.0600, description: "Public 18-hole golf course with river views" },
      { name: "Everett Crowley Park", type: "park", lat: 49.2150, lng: -123.0530, description: "Naturalized park with trails and city views" },
      { name: "Victoria Drive", type: "shopping", lat: 49.2300, lng: -123.0650, description: "Local shopping strip with diverse restaurants" },
    ],
  },
  strathcona: {
    name: "Strathcona",
    slug: "strathcona",
    center: { lat: 49.2750, lng: -123.0880 },
    zoom: 14,
    tagline: "Vancouver's Oldest Residential Neighbourhood",
    avgPrice: "$950K",
    priceChange: "-0.4% YoY",
    walkScore: 91,
    transitScore: 88,
    highlights: [
      "1890s heritage architecture",
      "Adjacent to historic Chinatown",
      "Strathcona Park & farmers market",
      "Artist studios & creative community",
    ],
    bounds: { north: 49.2850, south: 49.2650, east: -123.0730, west: -123.1030 },
    fallbackPOIs: [
      { name: "Main Street-Science World Station", type: "transit", lat: 49.2733, lng: -123.1005, description: "Expo & Millennium Line SkyTrain station" },
      { name: "Strathcona Park", type: "park", lat: 49.2760, lng: -123.0870, description: "Community park with playground, fields, and community garden" },
      { name: "CRAB Park at Portside", type: "park", lat: 49.2850, lng: -123.0900, description: "Waterfront park with harbour views" },
    ],
  },
};

export function getNeighbourhood(slug: string): NeighbourhoodData | undefined {
  return NEIGHBOURHOODS[slug];
}

export function getAllNeighbourhoods(): NeighbourhoodData[] {
  return Object.values(NEIGHBOURHOODS);
}

export const POI_ICONS: Record<PointOfInterest["type"], string> = {
  transit: "🚇",
  school: "🏫",
  park: "🌳",
  shopping: "🛍️",
  landmark: "📍",
  restaurant: "🍽️",
};
